name: 'user-bank'
services:
  user-service:
    image: feecruz/bank-user:1.3
    container_name: 'user-service-api'
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always

  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    ports:
      - '3307:3306'
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
    restart: always

