name: Publish JavaDoc

on:
  push: 
    branches: 
      ['main']

jobs:
  publish-javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of code
        uses: actions/checkout@v4

      - name: Java Configuration
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/reports/apidocs
          publish_branch: gh-pages